# Dynamic provisioning: no PV is created by hand.
# The "standard" StorageClass provisioner creates the PV automatically.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pvc
  namespace: session13
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
