apiVersion: v1
kind: Pod
metadata:
  name: dynamic-demo
  namespace: session13
spec:
  containers:
    - name: app
      image: nginx:1.27
      volumeMounts:
        - name: dynamic-storage
          mountPath: /data
  volumes:
    - name: dynamic-storage
      persistentVolumeClaim:
        claimName: dynamic-pvc
