apiVersion: v1
kind: Service
metadata:
  name: session20-gitops-app
  namespace: session20-gitops
spec:
  type: ClusterIP
  selector:
    app: session20-gitops-app
  ports:
    - port: 80
      targetPort: 80
